# -*- coding: utf-8 -*-
"""Exercícios9.PY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTwTWr-SctrCBN2Ue1KrF_LcOdSlPuRD
"""

# EXERCÍCIO 1 - SUBTRAÇÃO COM FUNÇÃO (DEF);

def sub (a,b):
  print(' A subtração é igual a =',a-b)
sub (20,10)

# EXERCÍCIO 2 - ADIÇÃO COM FUNÇÃO (DEF);

def adi (a,b):
  print(' A adição é igual a =',a+b)
adi (20,10)

# EXERCÍCIO 3- DIVISÃO COM FUNÇÃO (DEF);

def div (a,b):
  print(' A divisão é igual a =',a/b)
div (20,10)

# EXERCÍCIO 4 - MULTIPLICAÇÃO COM FUNÇÃO (DEF);

def mult (a,b):
  print(' A multiplicação é igual a =',a*b)
mult (20,10)

# EXERCÍCIO 4 - CALCULADORA ONDE O USUÁRIO POSSA ESCOLHER AS OPERAÇÕES (DEF);

def o ():

   print('Olá, seja bem vindo a nossa calculadora!')
   opcoes = int(input('Caso queira realizar um conta de ADIÇÃO pressione a tecla (1). SUBTRAÇÃO (2), DIVISÃO (3) e MULTIPLICAÇÃO (4)'))

   if opcoes == 1:
    ad('Adição')
   elif opcoes == 2:
    sub('Subtração')
   elif opcoes == 3:
    div('Divisão')
   elif opcoes == 4:
    mult('Multiplicação')
   else:
    print('Não temos essa opção...')

def ad (Adição):
    print('Você escolheu adição, legal!')
    valores1 = int(input('Digite um valor para sua adição : '))
    valores2 = int(input('Digite outro valor para sua adição : '))
    resultado1 = valores1 + valores2

    print('O resultado de {} + {} é igual a = {}'.format(valores1,valores2,resultado1))

def sub (Subtração):
    print('Você escolheu subtração, legal!')
    valores3 = int(input('Digite um valor para sua subtração : '))
    valores4 = int(input('Digite outro valor para sua subtração : '))
    resultado2 = valores3 - valores4

    print('O resultado de {} - {} é igual a = {}'.format(valores3,valores4,resultado2))

def div (Divisão):
    print('Você escolheu divisão, legal!')
    valores5 = int(input('Digite um valor para sua divisão : '))
    valores6 = int(input('Digite outro valor para sua divisão : '))
    
    if valores6 == 0:
      print('A divisão por "0" é impossível.')
    else:
      resultado3 = valores5 / valores6 
      print('O resultado de {} / {} é igual a = {}'.format(valores5,valores6,resultado3))

def mult (Multiplicação):
    print('Você escolheu multiplicação, legal!')
    valores7 = int(input('Digite um valor para sua multiplicação : '))
    valores8 = int(input('Digite outro valor para sua multiplicação : '))
    resultado4 = valores7 * valores8

    print('O resultado de {} x {} é igual a = {}'.format(valores7,valores8,resultado4))

o()
